### ISSUE TITLE
FeatureRequest: Kubernetes manifest

### ISSUE THREAD

**Issue by rdxmb** [greenbone/docs#238]
Hello, as there is a `docker-compose.yml` in your documentation, I am migrating it to a kubernets-manifest.

Are you interested in an PR for this docs?

As I am quite new to greenbone, I need some help about the connections needed between the containers/services. 

E.g. `docker-compose.yml` is here quite implicit in many cases, but for kubernetes I have to configure the ports the containers want to connect each other. There are also some other concrete questions I will ask when there is somebody who wants to support here. Please comment if you would like to contribute. Thanks and kind regards!

**Comment by bjoernricks** [comment]
Yes we are interested in a kubernetes deployment for our software stack. Therefore feel free to create a PR but currently I can't promise that it gets merged at the end because I don't know how much maintenance burden it will create. Just let us start and we will see what the future will bring us. You can ask question in this issue and I'll try to answer them.

**Comment by rdxmb** [comment]
Ok, sounds great!
Just to get the context: In kubernetes there is no `depends_on` like it is in docker-compose. I will try to do this with `initContainers`, as this is very common in kubernetes manifests.

First, I have to understand how the services in the docker-compose connect each other.

I assume that this is done via the service-names and the docker-dns. So the hostnames that will be connected are hardcoded in the images.

Example: 

The `image: greenbone/ospd-openvas` connects redis via its hostname `redis-server` and the default redis-port. Here it is quite obviously. 

However, I do not know about all the other stuff.

So first we have to define all the ports the services want to connect to each other. You could do that by commenting the ports in the `docker-compose.yml`, for example like this:

```
services:
  vulnerability-tests:   #  listens on port 6136
    image: greenbone/vulnerability-tests
    environment:
      STORAGE_PATH: /var/lib/openvas/22.04/vt-data/nasl
    volumes:
      - vt_data_vol:/mnt
  notus-data:    #  no network connection needed from the other containers
    image: greenbone/notus-data
    volumes:
      - notus_data_vol:/mnt
```

Could you support here? With this I will try to build the next step. Thanks and kind regards!
