### ISSUE TITLE
Having FEED_RELEASE: 24.10 without quotes gets interpreted in container as 24.1 in docker-compose.yml

### ISSUE THREAD

**Issue by gooseleggs** [greenbone/docs#549]
### Expected behavior
When starting up the container, it cannot find the NASL? files.  When running it says that it cannot find the files to copy/symlink in the containers.  This is due to docker interpreting the environment variable `24.10` as `24.1`.

To resolve change all references of `24.10` to `'24.10'` as per below

```
  vulnerability-tests:
    image: registry.community.greenbone.net/community/vulnerability-tests
    environment:
      FEED_RELEASE: 24.10
    volumes:
      - vt_data_vol:/mnt
```

to

```
  vulnerability-tests:
    image: registry.community.greenbone.net/community/vulnerability-tests
    environment:
      FEED_RELEASE: '24.10'
    volumes:
      - vt_data_vol:/mnt

```
